packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@next/bundle-analyzer': 16.1.0
  '@next/eslint-plugin-next': 16.1.0
  '@supabase/supabase-js': 2.89.0
  '@tailwindcss/postcss': 4.1.18
  '@tanstack/react-query': 5.90.12
  '@types/node': 25.0.3
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  eslint-config-next: 16.1.0
  next: 16.1.0
  react: 19.2.3
  react-dom: 19.2.3
  react-i18next: 16.5.0
  react-hook-form: 7.69.0
  supabase: 2.67.3
  tailwindcss: 4.1.18
  tw-animate-css: 1.4.0
  zod: 3.25.76

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
