packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@marsidev/react-turnstile': 1.4.2
  '@next/bundle-analyzer': 16.1.6
  '@next/eslint-plugin-next': 16.1.6
  '@react-email/components': 1.0.7
  '@sentry/nextjs': 10.38.0
  '@stripe/react-stripe-js': 5.6.0
  '@stripe/stripe-js': 8.7.0
  '@supabase/supabase-js': 2.95.3
  '@tailwindcss/postcss': 4.1.18
  '@tanstack/react-query': 5.90.20
  '@types/eslint': 9.6.1
  '@types/node': 25.2.1
  '@types/nodemailer': 7.0.9
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  eslint: 9.39.2
  eslint-config-next: 16.1.6
  eslint-config-turbo: 2.8.3
  i18next: 25.8.4
  i18next-browser-languagedetector: 8.2.0
  i18next-resources-to-backend: 1.2.1
  lucide-react: 0.563.0
  next: 16.1.6
  nodemailer: 8.0.0
  react: 19.2.4
  react-dom: 19.2.4
  react-hook-form: 7.71.1
  react-i18next: 16.5.4
  stripe: 20.3.1
  supabase: 2.75.5
  tailwindcss: 4.1.18
  tw-animate-css: 1.4.0
  zod: 4.3.6

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
