packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@marsidev/react-turnstile': 1.4.1
  '@next/bundle-analyzer': 16.1.3
  '@next/eslint-plugin-next': 16.1.3
  '@react-email/components': 1.0.4
  '@stripe/react-stripe-js': 5.4.1
  '@stripe/stripe-js': 8.6.1
  '@supabase/supabase-js': 2.90.1
  '@tailwindcss/postcss': 4.1.18
  '@tanstack/react-query': 5.90.19
  '@types/node': 25.0.9
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  eslint-config-next: 16.1.3
  i18next: 25.7.4
  i18next-browser-languagedetector: 8.2.0
  i18next-resources-to-backend: 1.2.1
  lucide-react: 0.562.0
  next: 16.1.3
  react: 19.2.3
  react-dom: 19.2.3
  react-hook-form: 7.71.1
  react-i18next: 16.5.3
  stripe: 20.2.0
  supabase: 2.72.8
  tailwindcss: 4.1.18
  tw-animate-css: 1.4.0
  zod: 3.25.76

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
