packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@next/bundle-analyzer': 16.0.2
  '@next/eslint-plugin-next': 16.0.2
  '@supabase/supabase-js': 2.84.0
  '@tailwindcss/postcss': 4.1.17
  '@tanstack/react-query': 5.90.10
  '@types/node': 24.10.1
  '@types/react': 19.2.6
  '@types/react-dom': 19.2.3
  eslint-config-next: 16.0.3
  next: 16.0.2
  react: 19.2.0
  supabase: 2.58.5
  tailwindcss: 4.1.17
  tw-animate-css: 1.4.0
  zod: 3.25.74

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
