packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@next/bundle-analyzer': 16.0.10
  '@next/eslint-plugin-next': 16.0.10
  '@supabase/supabase-js': 2.87.1
  '@tailwindcss/postcss': 4.1.18
  '@tanstack/react-query': 5.90.12
  '@types/node': 25.0.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  eslint-config-next: 16.0.10
  next: 16.0.10
  react: 19.2.3
  react-dom: 19.2.3
  supabase: 2.67.0
  tailwindcss: 4.1.18
  tw-animate-css: 1.4.0
  zod: 3.25.76

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
