packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@next/bundle-analyzer': 16.0.7
  '@next/eslint-plugin-next': 16.0.7
  '@supabase/supabase-js': 2.86.0
  '@tailwindcss/postcss': 4.1.17
  '@tanstack/react-query': 5.90.11
  '@types/node': 24.10.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  eslint-config-next: 16.0.7
  next: 16.0.7
  react: 19.2.1
  react-dom: 19.2.1
  supabase: 2.65.3
  tailwindcss: 4.1.17
  tw-animate-css: 1.4.0
  zod: 3.25.74

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
